### ISSUE TITLE
Passwords for events, departments, and shifts

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/laravel-voldb#27]
It would be nice if passwords could be used to restrict access to specific events, departments, and shifts. In the current Apogaea volunteer database, passwords are used on shifts to ensure only certain approved users are able to take some shifts.

This feature would also be expanded to include passwords for entire events, which could be useful for theme camps (issue #23).

**Comment by itsrachelfish** [comment]
This feature is deprecated by #35

**Comment by itsrachelfish** [comment]
Just talked to Sherpa from Elsewhence and they still really want this feature. Bringing it back from the dead. :skull:

**Comment by IzKen** [comment]
Umm.. This is required for Apo also... This has been in the VolDB since 2008... I know we can limit shifts by skills or something now, but within those roles shifts need to be password protected

**Comment by itsrachelfish** [comment]
Feature finished and on production now!
