### ISSUE TITLE
Relicense project

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/laravel-voldb#43]
I originally chose the MIT license when I created this project because it was a demo for learning the Laravel framework at my job. This project has grown quite a bit since then and has been approved by Apogaea. I think it would make sense to change the project to use the AGPL license, to ensure any derivatives of this work also support the burner community.

What do you think?

**Comment by devnill** [comment]
I like this idea. Affero is about as restrictive as free can be so it encourages transparency and openness from consumers of the voldb and it doesn't limit us from relicensing on a case by case basis.
