### ISSUE TITLE
Additional profile information

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/laravel-voldb#5]
**New Fields**
- [x] Full name
- [x] Burner name
- [x] Age
- [x] Phone
- [x] Emergency contact
- [x] Training documents
- [x] Last login
- [x] Camp

**New Behavior / Changes**
- [x] Update login_at date when user logs in (but not during registration)
- [x] Create separate pages for editing username / password / user data
- [x] Automatically redirect users to user data edit page after registering
- [x] Include information about uploading certification documents from the user profile page
- [x] Add all new fields into the profile templates
- [x] Prevent users from signing up for shifts without entering their full name

**Comment by IzKen** [comment]
In VolDB 2016 we only have:

email
Full name
Display name (aka nickname or burner name, I would just call this field Display name, since Burner name maynot be valid for some events in the future)
Phone
I have a ticket

So anything else is a nice to have for 2017. ER Contact seems like the most important one

**Comment by itsrachelfish** [comment]
We need to update the registration process to require certain fields like real name.

**Comment by IzKen** [comment]
I changed it from "real name" to "full name", I know many Burners will not give their real name. Even when we ask for "Legal Name" we get nicknames a lot :(  For the VolDB it's not critical that we have their real\legal name since it's just for the event.

**Comment by IzKen** [comment]
This seems to be in there already, I just edited mine. This is lower priority than password protected shifts at least, if it isn't fully done yet. Same for training documents, since password protected shifts are normally used for BAMF, Rangers, and other depts

**Comment by itsrachelfish** [comment]
Some of this information is already available in the system, but when talking with Dana she said it was really important that certain information like "full name" be required when registering so more detailed information is available when running reports.

**Comment by itsrachelfish** [comment]
This is finished and on production now. When a user registers they are automatically redirected to their profile to enter this information. If a user tries to sign up for a shift without entering their name, they are redirected to their profile.

An explanation about uploading EMT certifications was also added from the main profile page.
