### ISSUE TITLE
Edit Department does not work

### ISSUE THREAD

**Issue by chrisdobell** [playasoft/laravel-voldb#63]
Steps to reproduce:
 1. Go to https://volunteer.apogaea.com/department/2/edit
 2. Change the name from ASS to Ministry of Conformity
 3. Press the "Save Changes" button
 4.  The page sends and comes back with a 200 with the correct data but refreshes revert

**Comment by itsrachelfish** [comment]
@chrisdobell This is fixed as of ed141a1cf0e79af7a4ab496722aa39eb21fabf8c
