### ISSUE TITLE
Volunteer site needs a favico file

### ISSUE THREAD

**Issue by chrisdobell** [playasoft/laravel-voldb#64]
![apogaea_logo_2016_large_bw](https://cloud.githubusercontent.com/assets/25570108/24559439/e9b76400-15fb-11e7-98e9-f4683429e35a.png)
Make a small version of this file:
http://apogaea.com/wp-content/uploads/2016/01/Apogaea_logo_2016_large_BW.png

Add a favicon link similar to the following (to the main page template/view):

<link id="favicon" rel="shortcut icon" href="https://volunteer.apogaea.com/img/icons/favicon-32.png" sizes="16x16 32x32 48x48" type="image/png" />

**Comment by itsrachelfish** [comment]
@chrisdobell We could use the favicon file from the artgrants project? 

https://artgrants.apogaea.com/

**Comment by chrisdobell** [comment]
That will work :-)

**Comment by itsrachelfish** [comment]
Fixed as of 87028243dc67a0d9e6293d2ba088679787a8c31f
