### ISSUE TITLE
Shift role\training requirement not saving

### ISSUE THREAD

**Issue by IzKen** [playasoft/laravel-voldb#67]
When I setup the Board of Directors\On-Call shift I set it to require Department Lead.

I just checked and it was set to None. So I went to it: https://volunteer.apogaea.com/schedule/36/edit and clicked Department Lead and Save Changes. Then went back to it and it still had None.

**Comment by itsrachelfish** [comment]
This one was a bit tricky. This bug happens when choosing a role that is already the default roles for a shift.

**Comment by IzKen** [comment]
Got a work around to limit the "On Call" shifts for the Board?

I was trying to limit them to Shift Leads only and then giving the board this role and admin roles (for now).  But since it's not saving, these shifts could be taken by anyone currently.

We need a "Board Member" role added ideally, with the ~30 others that Chris will need to control who can grab what shifts.

**Comment by itsrachelfish** [comment]
This is fixed on production now :+1:
