### ISSUE TITLE
Bug: Have board-member role but still not allowed to take board shifts

### ISSUE THREAD

**Issue by chrisdobell** [playasoft/laravel-voldb#80]
Steps to reproduce:
 1. Create a user with board-member role but no admin role 
 2. Attempt to sign up for a board on-call shift (first one in list)
 3. You will get the error message as attached.
![board-member-role_case_sensitivity_bug](https://cloud.githubusercontent.com/assets/25570108/25532027/fb0892f8-2be8-11e7-9576-2e6118ce4885.png)

**Comment by itsrachelfish** [comment]
This was caused by the specific permissions that are manually defined in the AuthServiceProvider - https://github.com/playasoft/laravel-voldb/blob/master/laravel/app/Providers/AuthServiceProvider.php#L25-L68

I updated the slot code to check which user roles you have instead of these permissions.
