### ISSUE TITLE
Most popular camp report

### ISSUE THREAD

**Issue by itsrachelfish** [playasoft/laravel-voldb#85]
It would be cool to see a report of which camps everybody is planning on camping in according to users' profile data. This could be a good way to encourage camps to get more volunteers signed up.

**Comment by IzKen** [comment]
Cool to have features are low priority. Also things that weren't in the previous VolDB are low priority.

**Comment by psycho23** [comment]
DENIED/destroyed/shutDOWN. lol

**Comment by itsrachelfish** [comment]
This is a thing now! (Graph generated from report data)
![popular-camps-apo-2017](https://cloud.githubusercontent.com/assets/1670549/26753317/fe37a1f4-4820-11e7-8242-a2e682be1dc2.png)
